# https://prometheus.io/docs/prometheus/latest/command-line/prometheus/
# http://localhost:9090/

global:
  scrape_interval: 1s  # How often Prometheus scrapes targets
  evaluation_interval: 1s
  
scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector-gateway:8888']  # This must match the container name and exposed port
  - job_name: 'prometheus'
    static_configs:
      - targets: ['otel-collector-gateway:8889']  # This must match the container name and exposed port
  - job_name: 'socket.io'
    static_configs:
      - targets: ['end-user-1:5001']  # This must match the container name and exposed port
    